### ISSUE TITLE
AS 3.3.1 java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v8/renderscript/RenderScript;

### ISSUE THREAD

**Issue by netgb** [tianshaojie/android-library#2]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v8/renderscript/RenderScript;
        at com.eightbitlab.supportrenderscriptblur.SupportRenderScriptBlur.<init>(SupportRenderScriptBlur.java:29)
        at cn.skyui.app.MainActivity.initView(MainActivity.java:51)
        at cn.skyui.app.MainActivity.onCreate(MainActivity.java:44)

**Comment by netgb** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.skyui.app, PID: 10660
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v8/renderscript/RenderScript;
        at com.eightbitlab.supportrenderscriptblur.SupportRenderScriptBlur.<init>(SupportRenderScriptBlur.java:29)
        at cn.skyui.app.MainActivity.initView(MainActivity.java:51)
        at cn.skyui.app.MainActivity.onCreate(MainActivity.java:44)
        at android.app.Activity.performCreate(Activity.java:7210)
        at android.app.Activity.performCreate(Activity.java:7201)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v8.renderscript.RenderScript" on path: DexPathList[[zip file "/data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/base.apk", zip file "/data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_dependencies_apk.apk", zip file "/data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_resources_apk.apk", zip file "/data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_0_apk.apk", zip file "/data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_1_apk.apk", zip file "/data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_2_apk.apk", zip file "/data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_3_apk.apk", zip file "/data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_4_apk.apk", zip file "/data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_5_apk.apk", zip file "/data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_6_apk.apk", zip file "/data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_7_apk.apk", zip file "/data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_8_apk.apk", zip file "/data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/lib/arm64, /data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/base.apk!/lib/arm64-v8a, /data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:168)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 18 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/cn.skyui.app-8RIjpuB1ofmM5wzkWlfuiA==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:358)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:407)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:729)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:812)
        at android.app.LoadedApk.getResources(LoadedApk.java:1034)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2357)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5817)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        		... 6 more

**Comment by netgb** [comment]
android.useDeprecatedNdk=true
# 应用版本名称
VERSION_NAME=1.0.0
# 应用版本号
VERSION_CODE=1
# 支持库版本
#SUPPORT_VERSION=27.1.1
SUPPORT_VERSION=28.+
# MIN_SDK_VERSION
MIN_SDK_VERSION=16
# TARGET_SDK_VERSION
TARGET_SDK_VERSION=28
# BUILD_SDK_VERSION
COMPILE_SDK_VERSION=28
# BUILD_TOOLS_VERSION
BUILD_TOOLS_VERSION=28.0.3
